project:
  type: book
  resources:
    - /examples
    - favicon.ico
    - favicon.svg
    - favicon-96x96.png
    - apple-touch-icon.png
    - web-app-manifest-192x192.png
    - web-app-manifest-512x512.png
    - site.webmanifest
    - /media

website:
  llms-txt: true

book:
  favicon: favicon.ico
  title: "Slidecrafting"
  subtitle: "Making beautiful slides with reveal.js and Quarto"
  author: "Emil Hvitfeldt"
  date: "9/24/2025"
  repo-url: https://github.com/EmilHvitfeldt/slidecrafting-book.com
  site-url: https://slidecrafting-book.com
  open-graph: true
  repo-actions: [edit, issue, source]
  chapters:
    - index.qmd
    - part: "Theming"
      chapters:
        - 10-minute.qmd
        - colors.qmd
        - fonts.qmd
        - sizes.qmd
        - scss.qmd
        - theme.qmd
    - part: "Content"
      chapters:
        - elements.qmd
        - layout.qmd
        - manual-code.qmd
        - asciicast.qmd
    - part: "Interactivity"
      chapters:
        - fragments.qmd
    - part: "Extensions"
      chapters:
        - letterbox.qmd
        - codewindow.qmd
    - miscellaneous.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - styles.scss
    include-in-header: favicon-head.html
